"""Change place id to plac_id in associations model for placetype

Revision ID: 71d0fd4523c7
Revises: 9506bc5f363a
Create Date: 2023-10-09 13:52:16.226237

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71d0fd4523c7"
down_revision: Union[str, None] = "9506bc5f363a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "place_type_association_place_id_fkey",
        "place_type_association",
        type_="foreignkey",
    )

    op.alter_column(
        "place_type_association",
        "place_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None,
        "place_type_association",
        "place",
        ["place_id"],
        ["place_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "place_type_association", type_="foreignkey")
    op.create_foreign_key(
        "place_type_association_place_id_fkey",
        "place_type_association",
        "place",
        ["place_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "place_type_association",
        "place_id",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
