"""restoring Place-Location relationship

Revision ID: 9506bc5f363a
Revises: 7aeaa6bd3058
Create Date: 2023-10-08 14:11:03.443119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9506bc5f363a'
down_revision: Union[str, None] = '7aeaa6bd3058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'compound_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('location', 'global_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('uq_location_codes', 'location', type_='unique')
    op.add_column('place', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'place', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_column('place', 'location_id')
    op.create_unique_constraint('uq_location_codes', 'location', ['compound_code', 'global_code'])
    op.alter_column('location', 'global_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location', 'compound_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
