"""Remove location relationship from Place model

Revision ID: d6c4ebd80d1e
Revises: 59b8385f7550
Create Date: 2023-09-26 04:49:00.069719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c4ebd80d1e'
down_revision: Union[str, None] = '59b8385f7550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('place_location_id_fkey', 'place', type_='foreignkey')
    op.drop_column('place', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('place_location_id_fkey', 'place', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###
